# we are using separate workflow because CI producing test binaries with CPPFLAGS=-DTESTMODE

name: Elosys cli build - Windows cross compile 20.04


on:
  push:
    branches:
    - master
    - beta


jobs:

  windows-build:
    name: Windows Build (mingw)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Install deps (Windows)
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update  # prevents repo404 errors on apt-remove below
          sudo apt-get upgrade -y
          sudo apt-get install mingw-w64 build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool libncurses-dev unzip git python zlib1g-dev wget bsdmainutils automake libboost-all-dev libssl-dev libprotobuf-dev protobuf-compiler libqrencode-dev libdb++-dev ntp ntpdate nano software-properties-common curl libevent-dev libcurl4-gnutls-dev cmake clang libsodium-dev -y
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      - name: Build (Windows)
        run: |
          ./zcutil/build-win.sh -j$(nproc)
          zip --junk-paths elosys-win src/elosysd.exe src/elosys-cli.exe
      - name: Upload elosys-win.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: elosys-win
          path: ./elosys-win.zip
